- hosts: terraform-ansible
  tasks:
  - name: Instalando Última Versão Nginx
    apt: 
      pkg:
      - nginx
      update_cache: yes
    become: yes
  - name: Iniciando Nginx
    service:
      name: nginx
      state: started
      enabled: yes
  - name: Instalando o python3
    apt: 
      pkg:
      - python3
      update_cache: yes
    become: yes
  - name: Instalando o Java JDK
    apt:
      name: openjdk-11-jdk
      state: present
    become: yes
  - name: Instalando o GraphViz
    apt:
      name: graphviz
      state: present
    become: yes
  - name: Verificando se o repo sophya já existe
    stat:
      path: /home/ubuntu/repos/sophya/core/c4_generate.sh
    register: sophya
  - name: Clone o repositório do Sophya
    ansible.builtin.expect:
      chdir: /home/ubuntu/repos/
      command: git clone https://github.com/pablicio/sophya.git
      responses:
        Username: "pablicio"
        Password: "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"
    become: yes
    when: not sophya.stat.exists
  - name: Sincronizando o repositório do Sophya
    ansible.builtin.expect:
      chdir: /home/ubuntu/repos/sophya
      command: git pull
      responses:
        Username: "pablicio"
        Password: "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"
    become: yes
  - name: Verificando se o repo sophya web já existe
    stat:
      path: /var/www/sophya-web/package.json
    register: sophyaweb
  - name: Clone o repositório do Sophya Web
    ansible.builtin.expect:
      chdir: /var/www/
      command: git clone https://github.com/pablicio/sophya-web.git
      responses:
        Username: "pablicio"
        Password: "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"
    become: yes
    when: not sophyaweb.stat.exists
  - name: Sincronizando o repositório do Sophya Web
    ansible.builtin.expect:
      chdir: /var/www/sophya-web
      command: git pull
      responses:
        Username: "pablicio"
        Password: "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"
    become: yes
  - name: Configurando Doc Service com Nginx
    ansible.builtin.shell:
      chdir: /home/ubuntu/repos/sophya/iac/setup-server
      cmd: sh nginx_setup.sh
    become: yes