- hosts: terraform-ansible
  tasks:
  - name: Instalando o python3
    apt: 
      pkg:
      - python3
      update_cache: yes
    become: yes
  - name: Instalando o Java
    apt:
      name: "openjdk-11-jdk"
      state: present
    become: yes
  - name: Clone o repositório do Sophya
    ansible.builtin.expect:
      chdir: /home/ubuntu/repos/
      command: git clone https://github.com/pablicio/sophya.git 2>/dev/null
      responses:
        Username: "pablicio"
        Password: "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"
    become: yes
  - name: Sincronize o repositório do Sophya
    ansible.builtin.expect:
      chdir: /home/ubuntu/repos/sophya
      command: git pull
      responses:
        Username: "pablicio"
        Password: "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"
    become: yes
